### ISSUE TITLE
Review 1 - Week 6 Advanced Machine Learning 

### ISSUE THREAD

**Issue by okothchristopher** [BettyKagendo/Advanced-Machine-Learning#1]
1. The project lacks a Readme. This is not acceptable. 
2. Where did you get the data - If Kaggle, you need to disclose all the information about the data and your objective should be to achieve a better result than what is already implemented. 
3. You also need to check the project that is appropriate for this week. I believe the project was already changed. 
4. You need to suppress the warnings, they are making your notebook unreadable. 
5. What is the implication of the distribution of your numerical variables. 
6. Why have you done robust scaling. All these things have to have explanations. 
7. Why are you using Lasso, why is regularization important in this dataset. 
8. Why are you reducing dimensions. All these steps have to have justifications. 
9. What is the interpretation of the model outcomes, why is lasso performing better than ridge ETC. 
10. I would not advice you to tune a more complex model when it is performing only marginally better than a simple model. You just need to transform your data better to squeeze out the most performance you can get out of the simple model. It is usually easier to deploy such. 
11. Why are you using RandomSearch instead of Grid Search
12. You need to separate your training data from testing data, so that you can see model's performance on unseen data. 
13. What is the end result of your submission. What was your rank on Kaggle. This is missing.

**Comment by BettyKagendo** [comment]
Done
