### ISSUE TITLE
Review 1 - Customer Segementation Project

### ISSUE THREAD

**Issue by okothchristopher** [BettyKagendo/Advanced-Machine-Learning#2]
1. Same comment around maintaining a Readme remains. You need to have one for the main repo and for each folder, you have to have a detailed project readme. 
2. You also need to have a data description file in your folder, so one can infer what each field means. 
3. For each visualization, you need to have insights and deductions if applicable. Your notebook needs to have sections. 
4. This figure is outsized `#Explore the missingness msno.matrix(data[['Income']], figsize=(9,9))`
5. You need to uphold some of Jupyter notebooks best practices. You need to have comments for each of your steps. 
6. Why K- means when we have also covered other clustering methods, we know the limitations of K and we also know the limitations of K-means. 
7. Good work on visualizing your clusters with PCA. 
8. Why are there no development in this section. `Step 4: Interpretation and Recommendations Based on the cluster profiles, you can make data-driven marketing recommendations for each customer segment.`
9. How have you established that this is the most optimal cluster numbers.

**Comment by BettyKagendo** [comment]
Done
